name: CI/CD Pipeline TechWave

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c√≥digo
        uses: actions/checkout@v3

      - name: Gitleaks Scan (Seguridad)
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/techwave-app:latest .

      - name: Trivy Scan (Seguridad de Imagen)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/techwave-app:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/techwave-app:latest
